In [2]:
#stopwords.csv에서 띄어쓰기 있는 데이터 제거
import pandas as pd

stopwordss = pd.read_csv('C:\DeepLearing\Robot_KSG\poem\stopwords.csv', encoding='CP949')

stopwordss

In [12]:
for i in range(len(stopwordss)):
    for j in range(len(stopwordss.iloc[i])-1):
        if stopwordss.iloc[i, j].find(' ') != -1:
            stopwordss.iloc[i, j] = ''
            
stopwordss

stopword Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0         아         기타       불구하고         꽈당        어떤것        한다면          ㅅ   
1         휴       첫번째로       얼마든지         응당        NaN          등          ㄴ   
2       아이구       나머지는       마음대로       해야한다        NaN         등등          ㄹ   
3       아이쿠       그중에서        NaN        NaN       연관되다          제        을까요   
4       아이고       견지에서          곧          각       어떤것들         겨우        입니다   
..      ...        ...        ...        ...        ...        ...        ...   
95      반드시         윙윙        NaN         인젠         참나        그위에       까닭으로   
96     할줄알다         오호        NaN         이젠        그래서        게다가      이유만으로   
97     할수있다         아하          너       된바에야        NaN        NaN        가까이   
98     할수있어        어쨋든         너희        된이상       그러므로        NaN          랏   
99      NaN        NaN        NaN     만큼어찌됏든          령       고려하면        옵니다   

   Unnamed: 7  
0           은  
1           는  
2           께  
3           서  
4           인  
..        ...  
95        지마는  
96          거  
97         느니  
98         니다  
99        합니다  

[100 rows x 8 columns]

In [ ]:
stopwordss.to_csv('C:\DeepLearing\Robot_KSG\poem\stopwords.csv', index=False)

In [2]:
#시 1차 정제(줄바꿈/한문 등/특수문자)
import pandas as pd

poems = pd.read_csv('C:\DeepLearing\Robot_KSG\poem\poems.csv', names=['name', 'writer', 'text', 'cc'], sep=',')

poems[:3]

name writer                                               text  \
0  1, 2, 3, 4선생-1   서덕출   1,  2,  3,  4,  선생\n\n서덕출\n\n나는  학교  조그마한\n\n학...   
1         10월의 노래   조명희   10\n\n월의 노래\n\n짓밟힌 무리의 흘린 핏방울 방울이\n\n지심으로 흘러 흘...   
2            15일간   박인환   일간15\n\n깨끗한 시트 위에서\n\n나는 몸부림을 쳐도 소용이 없다.\n\n공간...   

        cc  
0  자유이용 만료  
1  자유이용 만료  
2  자유이용 만료

In [4]:
del(poems['cc'])

In [5]:
poems['text'] = poems['text'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣0-9,.!?\s]","")
poems['text'] = poems['text'].str.replace("\n+","\n")
poems['text'] = poems['text'].str.replace("\n.\n","")

In [6]:
poems.to_csv('C:\DeepLearing\Robot_KSG\poem\poems_preprocessing_v1.csv', index=False)

In [1]:
#test - MLP 전처리 연습
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

texts = [['먹고', '싶은', '사과'], ['먹고', '싶은', '바나나'], ['길고', '노란', '바나나', '바나나'], ['저는', '과일이', '좋아요']]
#토큰화 상태로 keras Tokenizer 진행 가능(불용어 제거한 토큰 상태인 데이터 사용 예정)
t = Tokenizer()
t.fit_on_texts(texts)
print(t.word_index)

{'바나나': 1, '먹고': 2, '싶은': 3, '사과': 4, '길고': 5, '노란': 6, '저는': 7, '과일이': 8, '좋아요': 9}


In [2]:
texts = ["['먹고', '싶은', '사과']", "['먹고', '싶은', '바나나']", "['길고', '노란', '바나나', '바나나']", "['저는', '과일이', '좋아요']"]

t = Tokenizer()
t.fit_on_texts(texts)
print(t.word_index)

{"'바나나'": 1, "'먹고'": 2, "'싶은'": 3, "'사과'": 4, "'길고'": 5, "'노란'": 6, "'저는'": 7, "'과일이'": 8, "'좋아요'": 9}


In [3]:
print(t.texts_to_matrix(texts, mode = 'count'))

[[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]
